### ISSUE TITLE
Aware of FastGaussQuadratures.jl?

### ISSUE THREAD

**Issue by juliohm** [JuliaFEM/FEMQuad.jl#11]
Did you consider using the FastGaussQuadrature.jl package? https://github.com/ajt60gaibb/FastGaussQuadrature.jl

One of the greatest things about the Julia community is the continuous effort to reuse highly optimized and well-tested packages for fundamental tools such as numerical integration.

**Comment by ahojukka5** [comment]
Yes I did look about it, but from FEM point of view it's quite useless because it does not have rules for triangles and tetrahedrons. For hexahedrons and quadrangles we get the rules easily by taking tensorial product of 1d rules.

In practice the calculation is done using quadratic tetrahedrons and there is 4 point integration rule. Other problem is that rules for triangular shape domains are not unique, for example there's two different rules for three quadrature points. Our approach is just to give label to rule and user can then decide what kind of schemes is constructed to FEM project. For example for JuliaFEM, we have the following:

https://github.com/JuliaFEM/JuliaFEM.jl/blob/master/src/integrate.jl

**Comment by juliohm** [comment]
I am aware of FEM peculiarities, it is been a while since the last time I coded them though. I just wanted to share the package because I would rather invest time extending a highly reusable package for integration than forking another package. This is one of my favorite things about the Julia community, we try to generalize and reuse things a lot. :+1: See DifferentialEquations, Optimization, etc. The greatest of the greatest stuff. :blush: 

I am closing the issue knowing that you are aware, thanks for the reply.
